/**
 * InsightsList - Container for AI-generated carbon reduction insights.
 */

import { useCarbonStore } from '../../store/carbonStore';
import type { InsightsResponse } from '../../types';
import { formatCategory, formatKg, toMonthlyKg } from '../../utils/formatters';
import { InsightCard } from './InsightCard';

interface InsightsListProps {
  insightsResponse: InsightsResponse;
}

export const InsightsList = ({ insightsResponse }: InsightsListProps) => {
  const { insights, source, total_potential_saving_kg } = insightsResponse;
  const saveEntry = useCarbonStore(s => s.saveEntry);
  const saveStatus = useCarbonStore(s => s.saveStatus);
  const saveMessage = useCarbonStore(s => s.saveMessage);

  const topInsight = insights[0];
  const monthlySaving = toMonthlyKg(total_potential_saving_kg);

  return (
    <section
      aria-labelledby="insights-heading"
      aria-live="polite"
      aria-atomic="false"
      className="space-y-5 animate-slide-up"
    >
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6">
        <div className="flex items-start justify-between flex-wrap gap-3">
          <div>
            <h2 id="insights-heading" className="text-xl font-bold text-gray-900 mb-1">
              Your Personalised Reduction Plan
            </h2>
            <p className="text-sm text-gray-500">
              A simple action path focused on your biggest carbon levers.
            </p>
          </div>
          {source === 'gemini' && (
            <span
              aria-label="Insights powered by Google Gemini AI"
              className="
                inline-flex items-center gap-1.5 text-xs font-semibold
                bg-gradient-to-r from-blue-50 to-primary-50
                text-primary-700 border border-primary-200
                px-3 py-1.5 rounded-full
              "
            >
              <span aria-hidden="true">AI</span>
              Powered by Google Gemini AI
            </span>
          )}
          {source === 'rules' && (
            <span
              aria-label="Insights generated by rule-based engine (Gemini AI unavailable)"
              className="
                inline-flex items-center gap-1.5 text-xs font-semibold
                bg-gray-50 text-gray-500 border border-gray-200
                px-3 py-1.5 rounded-full
              "
            >
              <span aria-hidden="true">Rules</span>
              Rule-based insights
            </span>
          )}
        </div>

        <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
          <div
            className="rounded-2xl border border-primary-100 bg-primary-50 p-4"
            aria-label={`Total potential annual saving: ${formatKg(total_potential_saving_kg)} CO2e`}
          >
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary-700">
              Total Potential
            </p>
            <div className="mt-2 text-3xl font-black text-primary-700">
              {formatKg(total_potential_saving_kg)}
            </div>
            <p className="mt-2 text-sm text-primary-800">
              If you implement all 3 actions below across the next year.
            </p>
          </div>

          <div className="rounded-2xl border border-gray-100 bg-white p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gray-500">
              First Move
            </p>
            <div className="mt-2 text-lg font-bold text-gray-900">
              {topInsight ? formatCategory(topInsight.category) : 'General'}
            </div>
            <p className="mt-2 text-sm text-gray-600">
              {topInsight?.action ?? 'No actions generated yet.'}
            </p>
          </div>

          <div className="rounded-2xl border border-gray-100 bg-white p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-gray-500">
              Monthly Momentum
            </p>
            <div className="mt-2 text-lg font-bold text-gray-900">{formatKg(monthlySaving)}</div>
            <p className="mt-2 text-sm text-gray-600">
              Average monthly reduction available if the full plan sticks.
            </p>
          </div>
        </div>

        {saveMessage && (
          <div
            className={`mt-4 rounded-xl border px-4 py-3 text-sm ${
              saveStatus === 'saved'
                ? 'border-green-200 bg-green-50 text-green-800'
                : saveStatus === 'error'
                  ? 'border-red-200 bg-red-50 text-red-700'
                  : 'border-gray-200 bg-gray-50 text-gray-600'
            }`}
          >
            {saveMessage}
          </div>
        )}
      </div>

      <ol
        aria-label="Personalized carbon reduction insights, ordered by priority"
        className="space-y-4 list-none"
      >
        {insights.map((insight, i) => (
          <li key={i}>
            <InsightCard insight={insight} index={i} />
          </li>
        ))}
      </ol>

      <div className="flex justify-center pt-2">
        <button
          onClick={saveEntry}
          disabled={saveStatus === 'saving'}
          className="
            flex items-center gap-2 text-sm text-gray-600 border border-gray-300
            px-5 py-2.5 rounded-xl hover:bg-gray-50 hover:border-gray-400
            focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2
            transition-all duration-200 disabled:opacity-70 disabled:cursor-not-allowed
          "
          aria-label="Save this carbon footprint snapshot to your history"
        >
          <span aria-hidden="true">Save</span>
          {saveStatus === 'saving'
            ? 'Saving...'
            : saveStatus === 'saved'
              ? 'Saved to History'
              : 'Save to History'}
        </button>
      </div>
    </section>
  );
};
