/**
 * SourceBadge - Displays the source of insights (AI or rules).
 */

import type { InsightsResponse } from '../../types';

interface SourceBadgeProps {
  source: InsightsResponse['source'];
}

export const SourceBadge = ({ source }: SourceBadgeProps) => {
  if (source === 'gemini') {
    return (
      <span
        aria-label="Insights powered by Google Gemini AI"
        className="
          inline-flex items-center gap-1.5 text-xs font-semibold
          bg-gradient-to-r from-blue-50 to-primary-50
          text-primary-700 border border-primary-200
          px-3 py-1.5 rounded-full
        "
      >
        <span aria-hidden="true">AI</span>
        Powered by Google Gemini AI
      </span>
    );
  }

  return (
    <span
      aria-label="Insights generated by rule-based engine (Gemini AI unavailable)"
      className="
        inline-flex items-center gap-1.5 text-xs font-semibold
        bg-gray-50 text-gray-500 border border-gray-200
        px-3 py-1.5 rounded-full
      "
    >
      <span aria-hidden="true">Rules</span>
      Rule-based insights
    </span>
  );
};
